version: '3.9'
networks:
  ox:
    ipam:
      driver: default
      config:
        - subnet: 192.168.17.0/24

services:
  oxweb:
    container_name: oxweb
    build:
      context: oxweb
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./oxweb/apache/sites-enabled/:/etc/apache2/sites-enabled/
      - ./oxweb/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./app:/var/www/ox/releases
      - ./config:/root/config/
      - ~/.ssh/:/root/.ssh
    ports:
      - "80:80"
    networks:
      ox:
        ipv4_address: 192.168.17.6
  oxdb:
    image: postgres:15-alpine
    container_name: oxdb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oxdb
    tty: true
    ports: ["5432"]
    volumes:
      - ./postgres:/var/lib/postgres/data
    networks:
      ox:
        ipv4_address: 192.168.17.5

  node:
    container_name: node
    build:
      context: node
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "3000:3000"
    networks:
      ox:
        ipv4_address: 192.168.17.7

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.13.0
    ports:
        - 9200:9200
        - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.security.enrollment.enabled=true
    networks:
      ox:
        ipv4_address: 192.168.17.8

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    depends_on:
      - elasticsearch
    entrypoint: ["./bin/kibana", "--allow-root"]
    networks:
      ox:
        ipv4_address: 192.168.17.9

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui
    networks:
      ox:
        ipv4_address: 192.168.17.10
