version: '3.9'
networks:
  ox:
    ipam:
      driver: default
      config:
        - subnet: 192.168.17.0/24

services:
  oxweb:
    container_name: oxweb
    hostname: oxweb
    build:
      context: oxweb
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./oxweb/apache/sites-enabled/:/etc/apache2/sites-enabled/
      - ./oxweb/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./app:/var/www/ox/releases
      - ./config:/root/config/
      - ~/.ssh/:/root/.ssh
    ports:
      - "80:80"
    networks:
      ox:
        ipv4_address: 192.168.17.6
  oxdb:
    image: postgres:15-alpine
    hostname: oxdb
    container_name: oxdb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oxdb
    tty: true
    ports: ["5432"]
    volumes:
      - ./postgres:/var/lib/postgres/data
    networks:
      ox:
        ipv4_address: 192.168.17.5

  node:
    container_name: node
    build:
      context: node
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "3000:3000"
    networks:
      ox:
        ipv4_address: 192.168.17.7

  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./api/app:/app
      - ~./m2:/root/m2
    ports:
      - "8080:8080"
    networks:
      ox:
        ipv4_address: 192.168.17.8